modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/Archers/issues"
license = "All Rights Reserved"

[[mods]]
modId = "archers"
version = "${version}"
displayName = "Archers (RPG Series)"
authors = "Daedelus"
description = '''
Draw, Release, Conquer - Master the art of Archery!
'''
logoFile = "icon.png"

[[dependencies.archers]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archers]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archers]]
modId = "azurelibarmor"
type = "required"
versionRange = "[${azure_lib_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archers]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.archers]]
modId = "bundleapi"
type = "required"
versionRange = "[${bundle_api_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.archers]]
modId = "ranged_weapon_api"
type = "required"
versionRange = "[${ranged_weapon_api_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "archers.mixins.json"
